"""new technical experience model

Revision ID: 06de6cb49eb9
Revises: fe98c9efe66b
Create Date: 2018-02-23 01:09:35.388401

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '06de6cb49eb9'
down_revision = 'fe98c9efe66b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_experience',
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('items', sa.PickleType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_experience')
    # ### end Alembic commands ###
