"""modified user model

Revision ID: 08893fd6a7fa
Revises: 06de6cb49eb9
Create Date: 2018-02-23 03:19:26.357389

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '08893fd6a7fa'
down_revision = '06de6cb49eb9'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_api_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.Unicode(length=127), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.Unicode(length=127), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Unicode(length=127), nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.Unicode(length=127), nullable=True))
        batch_op.add_column(sa.Column('website', sa.Unicode(length=127), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.Unicode(length=127), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_api_user', schema=None) as batch_op:
        batch_op.drop_column('zip')
        batch_op.drop_column('website')
        batch_op.drop_column('street_address')
        batch_op.drop_column('state')
        batch_op.drop_column('phone')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
