"""add client model

Revision ID: 3e0935cc04e5
Revises: 580facb050ac
Create Date: 2018-02-17 00:16:58.050784

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3e0935cc04e5'
down_revision = '580facb050ac'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_client',
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=22), nullable=False),
    sa.Column('secret_key', sa.Unicode(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_client')
    # ### end Alembic commands ###
