"""updating user model with a username

Revision ID: 4ae66d0e1825
Revises: 08893fd6a7fa
Create Date: 2018-03-12 22:05:29.439223

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4ae66d0e1825'
down_revision = '08893fd6a7fa'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_api_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.Unicode(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_api_user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
