"""weapon_of_choice and school models

Revision ID: d49725ce8f3b
Revises: 3e0935cc04e5
Create Date: 2018-02-22 02:47:15.404524

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd49725ce8f3b'
down_revision = '3e0935cc04e5'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('school_name', sa.Unicode(length=255), nullable=False),
    sa.Column('wut', sa.Unicode(length=255), nullable=False),
    sa.Column('date_of_graduation', sa.Unicode(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon_of_choice',
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('items', sa.PickleType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon_of_choice')
    op.drop_table('school')
    # ### end Alembic commands ###
