"""Just a test to see what a migration actually does (employment experience model)

Revision ID: fe98c9efe66b
Revises: f58d3c4d343a
Create Date: 2018-02-22 22:00:52.673253

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fe98c9efe66b'
down_revision = 'f58d3c4d343a'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.PickleType(), nullable=False))
        batch_op.drop_column('responsibilities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsibilities', sa.BLOB(), nullable=False))
        batch_op.drop_column('items')

    # ### end Alembic commands ###
